# Generated by Django 3.2.4 on 2021-06-13 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20210613_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Added'),
        ),
    ]
