# Generated by Django 3.2.4 on 2021-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertytype',
            field=models.CharField(choices=[('FOR_SALE', 'For Sale'), ('FOR_RENT', 'For Rent')], default='FOR_SALE', max_length=10),
        ),
    ]
