# Generated by Django 3.2.4 on 2021-06-14 18:03

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertygalleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='overview',
            new_name='property_description',
        ),
        migrations.AlterField(
            model_name='propertygalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property'),
        ),
    ]
