# Generated by Django 3.2.4 on 2021-06-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20210614_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='none', unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('FOR SALE', 'For Sale'), ('FOR RENT', 'For Rent')], default='FOR_SALE', max_length=10),
        ),
    ]
