# Generated by Django 3.2.4 on 2021-07-15 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210621_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='actual_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Time Added'),
        ),
    ]
