# Generated by Django 3.2.4 on 2021-07-15 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_property_actual_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='actual_datetime',
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Added'),
        ),
    ]
