# Generated by Django 3.2.4 on 2021-12-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_videolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
