# Generated by Django 3.2.4 on 2021-12-29 17:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_videolink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_links', to='property.property'),
        ),
    ]
