# Generated by Django 3.2.4 on 2022-01-03 07:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_videolink_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolink',
            old_name='link',
            new_name='video',
        ),
        migrations.CreateModel(
            name='MapLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.TextField(null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='map_link', to='property.property')),
            ],
        ),
    ]
