# Generated by Django 3.2.4 on 2021-06-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='page_subtitle',
            field=models.CharField(default='page sub-title', max_length=250),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='page_title',
            field=models.CharField(default='page title', max_length=250),
        ),
    ]
