# Generated by Django 3.2.4 on 2021-06-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='header_one',
        ),
    ]
