# Generated by Django 3.2.4 on 2021-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_header_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_two',
            field=models.CharField(default='Your trusted county experts in pre-verified properties.', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_one',
            field=models.CharField(default='Find Land for Sale', max_length=250),
        ),
    ]
